title: my open source work in progress
email: rafvasq21@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a shared collection of Rafael Vasquez's open source and tech thoughts and content.
url: "https://rafvasq.github.io" # the base hostname & protocol for your site
twitter_username: rafvasq
github_username:  rafvasq

# Build settings
author: Rafael Vasquez
theme: minima
paginate: 10          # Posts per page on the blog index
pagination_dir: "/blog/page:num/"  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 10       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
plugins: [jekyll-paginate]
exclude: [vendor]
gems: ["jekyll-gist","jekyll-paginate", "jekyll-sitemap", "rouge"]

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
git:
  branch: master